version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - .:/.bd_data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  celery:
    build: .
    command: celery -A liberiasUSB worker --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

