# Generated by Django 4.1.7 on 2023-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_load', models.CharField(choices=[('SALES REPORT', 'Reporte de ventas por Libreria'), ('TOP_SELLING_BOOOKS', 'Top de libros vendidos')], max_length=50, verbose_name='Tipo de reporte')),
                ('created_at', models.DateTimeField(verbose_name='Fecha de creación')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('FAILURE', 'Fracaso'), ('SUCCESS', 'Exito')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('task_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de ejecución')),
            ],
            options={
                'verbose_name': 'Tarea de Reporte',
                'verbose_name_plural': 'Tareas de Reportes',
            },
        ),
    ]
