# Generated by Django 4.1.7 on 2023-03-29 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Publicacion')),
                ('authors', models.ManyToManyField(to='librerias.author')),
            ],
        ),
        migrations.CreateModel(
            name='Bookshop',
            fields=[
                ('nit', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nit')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Razon Social')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto')),
                ('celphone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número de celular')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencias')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='librerias.book')),
                ('bookshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='librerias.bookshop')),
            ],
        ),
    ]
